// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTXKG9nuzu0-l-9VHX_MwpgpQiPvTflWQ',
    appId: '1:381319058495:web:458dc567203d64adef948a',
    messagingSenderId: '381319058495',
    projectId: 'temp-783ae',
    authDomain: 'temp-783ae.firebaseapp.com',
    databaseURL: 'https://temp-783ae-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'temp-783ae.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYTlP93HnL2x74sRSZpfU7UyA5_aPWAgo',
    appId: '1:381319058495:android:bba650d4b14cdc31ef948a',
    messagingSenderId: '381319058495',
    projectId: 'temp-783ae',
    databaseURL: 'https://temp-783ae-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'temp-783ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1JNcttE8RYISn2mcc2BKU8x-x2UBt-EE',
    appId: '1:381319058495:ios:0585e1dedfb291bfef948a',
    messagingSenderId: '381319058495',
    projectId: 'temp-783ae',
    databaseURL: 'https://temp-783ae-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'temp-783ae.appspot.com',
    iosBundleId: 'com.example.esp32FirebaseMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1JNcttE8RYISn2mcc2BKU8x-x2UBt-EE',
    appId: '1:381319058495:ios:0585e1dedfb291bfef948a',
    messagingSenderId: '381319058495',
    projectId: 'temp-783ae',
    databaseURL: 'https://temp-783ae-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'temp-783ae.appspot.com',
    iosBundleId: 'com.example.esp32FirebaseMobileApp',
  );
}
